config/routes.rb
Rails.application.routes.draw do
  get 'notifications/index'
  get 'rooms/index'
  get 'posts_feed/create'
  get 'posts_feed/store'
  get 'posts_feed/index'
  post 'posts_feed/store'
  get 'posts_feed/destroy'
  get '/posts_feed/destroy/:id', to: 'posts_feed#destroy', as: 'destroy_post'

  resources :posts_feed do
    
  end

  resources :contacts
  
  resources :rooms do
    resources :messages
  end
  get 'chats/create'
  get 'chats/new'
  get 'chats/show'
  get 'chats/index'
  devise_for :users, controllers: {
    sessions: 'user/sessions',
    registrations: 'user/registrations',
    omniauth_callbacks: 'user/omniauth_callbacks',
    confirmations: 'user/confirmations',
    unlocks: 'user/unlocks'
  }

  devise_scope :user do
    get 'login', to: 'devise/sessions#new' #change route from /users/sign_in to /login
    get 'users/sign_out', to: 'users/sessions#destroy'
    get 'signup', to: 'devise/registrations#new' #change route from /users/signup to /signup

    #get '/users/auth/:provider/passthru', to: 'user/omniauth_callbacks#passthru', as: :user_omniauth_passthru
    #get "/users/auth/google_oauth2" => "users/omniauth_callbacks#passthru"

  end
  resources :users, only: [:show], path: 'profile'

  resources :notifications, only: [:index]

  resources :posts do
    member do
      post 'add_like', to: 'posts#add_like', as: 'add_like_post'
    end
    get 'posts', to: 'posts#index', as: 'posts'

  end
        
  resources :chats do
    get 'chats', to: 'chats#index', as: 'chats'
  end
  
  #get 'posts/:id/add_like', to: 'posts#add_like', as: 'add_like_post'

  root 'welcome#index'
  
end

app/models/posts_feed.rb
class PostsFeed < ApplicationRecord
    validates :category, presence: true
end

app/controllers/posts_feed_controller.rb
    # app/controllers/post_controller.rb
    class PostsFeedController < ApplicationController
      def show
        @post = PostsFeed.find(params[:id])
        # Additional logic if needed

        redirect_to posts_feed_index_path
      end

      def index
        @posts_feed = PostsFeed.all.order("created_at DESC")
      end

      def destroy
        @post = PostsFeed.find(params[:id])
               

        if @post
          puts "Deleting post with ID: #{@post.id}"
          @post.destroy
          redirect_to posts_feed_index_path, notice: 'Post was successfully deleted.'
        else
          redirect_to posts_feed_index_path, alert: 'Post not found.'
        end
      end
      
      def create
      end
    
      def store
        #puts "Category: #{params[:category]}"
        #@image = params[:media] ? Cloudinary::Uploader.upload(params[:media]) : Cloudinary::Uploader.upload(default_media_url(params[:category]))
        #puts "Cloudinary Upload Response: #{@image}"
        # upload image to cloudinary
        #@image = Cloudinary::Uploader.upload(params[:media])
        
        # create a new post object and save to db
        #@post = PostsFeed.new({:title => params[:title], :body => params[:body], :author => params[:author], :category => params[:category],  :media => @image['secure_url']})

        # Check if the category is "Social" and if a file is present
        if params[:category] == "Social Input" && params[:media].present?
          # Handle file upload for "Social" category
          uploaded_file = params[:media]
          cloudinary_response = Cloudinary::Uploader.upload(uploaded_file)

          # Create a new post object and save to db
          @post = PostsFeed.new({
            title: params[:title],
            body: params[:body],
            author: params[:author],
            category: params[:category],
            media: cloudinary_response['secure_url']
          })
        else
          # For other categories or when no file is provided
          @post = PostsFeed.new({
            title: params[:title],
            body: params[:body],
            author: params[:author],
            category: params[:category],
            media: default_media_url(params[:category])
          })
        end
       
        if @post.save
          # broadcasting posts using pusher
          Pusher.trigger('posts-channel','new-post', {
            id: @post.id,
            title: @post.title,
            media: @post.media,
            body: @post.body,
            category: @post.category
          })
        end 
        
        redirect_to posts_feed_index_path
      end

      
      #app/assets/images/question_mark.png
      #Helper method to get default media URL based on category
      def default_media_url(category)
        case category
          when "Questions"
            "https://res.cloudinary.com/dhgdirwff/image/upload/v1705937228/question_mark_hogwlx.png"
          when "Announcements"
            "https://res.cloudinary.com/dhgdirwff/image/upload/v1705937228/announcement_rzazi4.png"
        end
      end
    end

app/helpers/posts_feed_helper.rb
module PostsFeedHelper
end

app/views/posts_feed/create.html.erb
    <!-- app/views/post/create.html.erb -->
    <style>
    .title {
        text-align: center;
        color:green;
    }
           
    .post-form{
        display: flex;
        width: 50%;
        flex-direction: column;
        margin: 20px auto;
    }
    .form-group{
        display: flex;
        justify-content: space-between;
        margin: 5px 0px;
        align-items: center;
    }
    
    input[type="submit"]{
        background-color: #333333;
        border: none;
        color: white;
        padding: 10px 32px;
        text-align: center;
        text-decoration: none;
        display: inline-block;
        font-size: 16px;
    }

    </style>
    <div class="title" >
        <h1>Live Blog</h1>
        <p>Editor View</p>
    </div>
    
    <div style="text-align:center">
        <p><strong>Fill and submit the form below to create a new post</strong></p>
        <p><strong>NOTE: If you want to create a <i>Questions</i> or <i>Announcements</i> post, do not upload any picture!</strong><p>
    
        <form method="POST" action="/posts_feed/store" enctype="multipart/form-data" class="post-form">
            <%= token_tag %>
    
            <div class="form-group">
                <label for="title">Title</label>
                <input type="text" name="title" class="form-control">
            </div>
            <div class="form-group">
                <label for="media">Post Media</label>
                <!-- <input type="file" name="media" class="form-control media-upload"> -->
                <input type="file" name="media" class="form-control media-upload" id="media-input">
                
                <img src="" alt="Image Preview" id="image-preview" style="max-width: 100%; max-height: 200px; display: none;">
            </div>
            <div class="form-group">
                <label for="author">Post Author</label>

                <% if user_signed_in? %>
                <!--<div>
                    <p>Debugging: Current User Information</p>
                    <pre><%= current_user.to_s %></pre>
                </div>-->
                    <% if current_user.provider == 'google' %>
                    <!-- If logged in via Google, use the email as the author -->
                        <input type="text" name="author" class="form-control" value="<%= current_user.email %>" />
                    <% else %>
                    <!-- If logged in via other methods, use the username if available -->
                    <input type="text" name="author" class="form-control" value="<%= current_user.name if current_user.name.present? %>" />
                    <% end %>
                <% end%>
            </div> 
            
            <div class="form-group">
                <label for="body">Post Content</label>
                <textarea name="body" class="form-control" cols="30" rows="10"></textarea>
            </div>

            <div class="form-group">
                <label for="category">Post Category</label>
                <%= select_tag "category", options_for_select(["Announcements", "Questions", "Social Input"]), class: "form-control",id: "category-select" %>
                <!--<input type="hidden" name="selectedCategory" id="selected-category"> -->

            </div>
            <div class="from-group">
                <div><input type="submit" value="Create Post"></div>
            </div>
            <br>
            <div>
               <%= link_to 'Back to Feed', posts_feed_index_path, id: 'posts-link'%>
            </div>
        </form>
    
    </div>

    
   

app/views/posts_feed/index.html.erb
    <style>
            
    * {
      font-family: "Lora", serif;
    }
    
    .title {
      text-align: center;
    }
    
    .posts {
      margin-top: 50px;
      display: flex;
      flex-direction: row;  
      justify-content: space-around;
      flex-wrap: wrap;
    }
    
    .post-card {
      display: flex;
      flex-direction: column;
      min-width: 300px;
      max-width: 300px;
      height: 400px;
      box-shadow: 1px 1px rgb(68, 68, 68);
      border: 1px solid rgb(68, 68, 68);
      border-radius: 5px;
      margin: 20px 0px;
    }
    
    .image {
      width: 100%;
      height: 170px;
    }
    
    .body-trunc {
      margin-left: 10px;
      margin-right: 10px;
    }

    .new-post{
        display: flex;
        justify-content: space-between;
        margin: 5px 0px;
        align-items: center;
        
    }

    </style>
    <script>
        var pusher = new Pusher('YOUR_APP_KEY', {
          cluster: 'eu',
          encrypted: true
        });
    </script>
    
    <div class="wrapper">
        <div class="title">
            <h1 style="color:green;">Main Feed  </h1>
            <p> <em> New posts will be displayed in realtime </em></p>
            
            <!--<%= link_to 'Create A New Post', posts_feed_create_path, id: 'posts-link'%>-->
            <button id="myButton" >Create A New Post</button>
            <br>
            <div class="sort-options">
                <label for="sortSelect">Sort by:</label>
                <select id="sortSelect" onchange="sortPosts()">
                    <option value="original">Original Order</option>
                    <option value="category">Category</option>
                    <option value="date">Date</option>
                </select>
            </div>
            <div class="search-author">
                <label for="authorSearch">Search by Author:</label>
                <input type="text" id="authorSearch" placeholder="Enter author's name">
                <button onclick="searchByAuthor()">Search</button>
            </div>
        </div>
    
        <div class="posts" id="post_section">
            <% @posts_feed.each do |post| %>
                <div class="post-card">
                    <img class="image" src="<%= post.media %>">
                    <div class="title">
                        <h2><%= post.title %></h2>
                    </div>
                    <div class="body-trunc">
                        <p><%= post.body %></p>
                    </div>
                    <div class="body-trunc">
                        <p> Category of post: <strong><%= post.category%></strong> </p>
                    </div>
                    <div class="body-trunc">
                        <p> Posted by: <em> <%= post.author%> </em></p>
                    </div>
                    <div class="body-trunc date" >
                        <p>Created on: <%= post.created_at.strftime("%B %d, %Y %I:%M %p") %></p>
                    </div>
                    <div class="body-trunc">
                        <% if current_user && (current_user.name == post.author || current_user.email == post.author) %>
                            <%= link_to 'Delete Post', destroy_post_path(post.id), data: { confirm: 'Are you sure?' } %>
                        <% end %>
                    </div>
                </div>
            <% end %>
        </div>
    </div>  
    
    <script>
        var channel = pusher.subscribe('posts-channel');
        channel.bind('new-post', function(data) {
            let post_media = data.media;
            let post_id = data.id
            let post_body = data.body;
            let post_title = data.title;
    
            let div = document.getElementById('post_section');
            let new_content = document.createElement("div");
            new_content.innerHTML = `
                <div class="post-card">
                    <img class="image" src="${post_media}">
                    <div class="title">
                        <h2>${post_title}</h2>
                    </div>
                    <div class="body-trunc">
                        <p>${post_body}</p>
                    </div>
                </div>`;
            div.insertBefore(new_content, div.firstChild);
        });

        document.getElementById("myButton").onclick = function () {
            location.href = "http://localhost:3000/posts_feed/create";
    };
    var originalOrder = Array.from(document.getElementsByClassName("post-card"));

    function sortPosts() {
        var sortSelect = document.getElementById("sortSelect");
        var sortBy = sortSelect.value;

        // Get the post section container
        var postSection = document.getElementById("post_section");

        // Get all post cards
        var postCards = postSection.getElementsByClassName("post-card");

        // Convert HTMLCollection to Array for easier manipulation
        var postArray = Array.from(postCards);

        // Sort the posts based on the selected option
        if (sortBy === "original") {
            // Sort by the original order (do nothing, as posts are already in the original order)
            postArray = originalOrder;
        } else if (sortBy === "category") {
            postArray.sort((a, b) => {
                var categoryA = a.querySelector('.body-trunc strong').innerText.toLowerCase();
                var categoryB = b.querySelector('.body-trunc strong').innerText.toLowerCase();
                return categoryA.localeCompare(categoryB);
            });
        } else if (sortBy === "date") {
            postArray.sort((a, b) => {
                // Add your logic to extract and compare date information from posts
                // For simplicity, assuming the date is in a specific format
                var dateA = new Date(a.querySelector('.date').innerText);
                var dateB = new Date(b.querySelector('.date').innerText);
                return dateA - dateB;
            });
        }

        // Remove existing posts from the container
        while (postSection.firstChild) {
            postSection.removeChild(postSection.firstChild);
        }

        // Append sorted posts back to the container
        postArray.forEach((post) => {
            postSection.appendChild(post);
        });
    }

     function searchByAuthor() {
        var authorSearchInput = document.getElementById("authorSearch");
        var authorName = authorSearchInput.value.toLowerCase();

        // Get all post cards
        var postCards = document.getElementsByClassName("post-card");

        // Iterate through each post card and show/hide based on author name
        for (var i = 0; i < postCards.length; i++) {
            var postAuthor = postCards[i].querySelector('.body-trunc em').innerText.toLowerCase();
            var displayStyle = (postAuthor.includes(authorName)) ? 'flex' : 'none';
            postCards[i].style.display = displayStyle;
        }
    }
    </script> 

app/views/posts_feed/show.html.erb
<h1><%= @post.title %></h1>
<p><%= @post.body %></p>
<p><%= @post.category%> </p>
<p> id: <%= @post.id%> </p>
<!-- Other post details -->

app/views/posts_feed/store.html.erb
<h1>PostsFeed#store</h1>
<p>Find me in app/views/posts_feed/store.html.erb</p>