config/routes.rb
Rails.application.routes.draw do
  get 'notifications/index'
  get 'rooms/index'
  get 'posts_feed/create'
  get 'posts_feed/store'
  get 'posts_feed/index'
  post 'posts_feed/store'
  get 'posts_feed/destroy'
  get '/posts_feed/destroy/:id', to: 'posts_feed#destroy', as: 'destroy_post'

  resources :posts_feed do
    
  end

  resources :contacts
  
  resources :rooms do
    resources :messages
  end
  get 'chats/create'
  get 'chats/new'
  get 'chats/show'
  get 'chats/index'
  devise_for :users, controllers: {
    sessions: 'user/sessions',
    registrations: 'user/registrations',
    omniauth_callbacks: 'user/omniauth_callbacks',
    confirmations: 'user/confirmations',
    unlocks: 'user/unlocks'
  }

  devise_scope :user do
    get 'login', to: 'devise/sessions#new' #change route from /users/sign_in to /login
    get 'users/sign_out', to: 'users/sessions#destroy'
    get 'signup', to: 'devise/registrations#new' #change route from /users/signup to /signup

    #get '/users/auth/:provider/passthru', to: 'user/omniauth_callbacks#passthru', as: :user_omniauth_passthru
    #get "/users/auth/google_oauth2" => "users/omniauth_callbacks#passthru"

  end
  resources :users, only: [:show], path: 'profile'

  resources :notifications, only: [:index]

  resources :posts do
    member do
      post 'add_like', to: 'posts#add_like', as: 'add_like_post'
    end
    get 'posts', to: 'posts#index', as: 'posts'

  end
        
  resources :chats do
    get 'chats', to: 'chats#index', as: 'chats'
  end
  
  #get 'posts/:id/add_like', to: 'posts#add_like', as: 'add_like_post'

  root 'welcome#index'
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/chat.rb
class Chat < ApplicationRecord
    after_create :notify_pusher
    
    def notify_pusher
        Pusher.trigger('chat', 'new', self.as_json)
    end
    end

app/models/contact.rb
class Contact < ApplicationRecord
    belongs_to :user

    validates :name, :email, :phone, presence: true
end

app/models/like.rb
class Like < ApplicationRecord
  after_save :notify_pusher
  belongs_to :post
  
  def notify_pusher
    Pusher.trigger('feed', 'new-like', self.post.as_json(include: :likes))
  end
end
    
    

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :room
  after_create_commit { broadcast_append_to self.room }
  before_create :confirm_participant

  has_noticed_notifications

  after_create_commit :notify_user

  def notify_user
    MessageNotifier.with(message: self).deliver_later(user)
  end
  
  def confirm_participant
    if self.room.is_private
      is_participant = Participant.where(user_id: self.user.id, room_id: self.room.id).first
      throw :abort unless is_participant
    end
  end
end

app/models/participant.rb
class Participant < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/post.rb
class Post < ApplicationRecord
    after_create :notify_pusher
    has_many :likes
    
    def notify_pusher
        Pusher.trigger('feed', 'new-post', self.as_json(include: :likes))
    end
end


    

app/models/posts_feed.rb
class PostsFeed < ApplicationRecord
    validates :category, presence: true
end

app/models/room.rb
class Room < ApplicationRecord
    validates_uniqueness_of :name
    scope :public_rooms, -> { where(is_private: false) }
    after_create_commit {broadcast_append_to "rooms"}
    has_many :messages

    has_many :participants, dependent: :destroy
    after_create_commit { broadcast_if_public }

    def broadcast_if_public
    broadcast_append_to "rooms" unless self.is_private
    end

    def self.create_private_room(users, room_name)
    single_room = Room.create(name: room_name, is_private: true)
    users.each do |user|
        Participant.create(user_id: user.id, room_id: single_room.id )
    end
    single_room
    end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :contacts
  has_many :messages
  
  validates_uniqueness_of :name
  
  has_many :noticed_notifications, as: :recipient
  #after_create_commit { broadcast_append_to "users" }
  scope :all_except, ->(user) { where.not(id: user.id) }

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, omniauth_providers: [:google_oauth2]

  def self.from_google(u)
    Rails.logger.debug "User.from_google - Input parameters: #{u.inspect}"
    create_with(uid: u[:uid], provider: 'google',
                password: Devise.friendly_token[0, 20], name: u[:name]).find_or_create_by!(email: u[:email])
  end   
end

app/controllers/chats_controller.rb
      
class ChatsController < ApplicationController
  def index
    @chats = Chat.all
    @chat = Chat.new
  end
  
  def new
    @chat = Chat.new
  end
  
  def create
    @chat = Chat.new(chat_params)
    respond_to do |format|
      if @chat.save
        format.html { redirect_to @chat, notice: 'Message was successfully posted.' }
        format.json { render :show, status: :created, location: @chat }
      else
        format.html { render :new }
        format.json { render json: @chat.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    def chat_params
      params.require(:chat).permit(:username, :message)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  skip_before_action :verify_authenticity_token, only: :add_like
  def index
    @posts = Post.all.order(created_at: :desc)
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.likes.build()
    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  def add_like
    @post = Post.find(params[:id])
    if @post
      @post.likes[0].like_count += 1

      if @post.likes[0].save
        respond_to do |format|
          format.html { redirect_to @post, notice: 'Like was successfully created.' }
          format.json { render json: { post: @post, likes: @post.likes[0].like_count }, status: :ok }
        end
      else
        format.json { render json: @post.likes[0].errors, status: :unprocessable_entity }
      end
    else
      format.json { render json: { error: 'Post not found' }, status: :not_found }
    end
  end

  def show 
    @post = Post.find(params[:id])
    render json: @post, methods: [:likes]
  end

  private

  def post_params
    params.require(:post).permit(:post, :username)
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  def index
    @current_user = current_user
    redirect_to '/login' unless @current_user
    @users = User.all;
    @rooms = Room.public_rooms
    @room = Room.new

    
  end

  def create
    @room = Room.create(name: params["room"]["name"])
  end

  def show
    @current_user = current_user
    @single_room = Room.find(params[:id])
    @rooms = Room.public_rooms
    @users = User.all_except(@current_user)
    @room = Room.new
    @message = Message.new
  
    render "index"
  end


end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  
end

app/helpers/application_helper.rb
module ApplicationHelper
    include NavigationHelper
    include PostsHelper    
    def active_class(path)
        if request.path == path
          return 'active'
        else
          return ''
        end
      end
end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/navigation_helper.rb
module NavigationHelper

    def collapsible_links_partial_path
      if user_signed_in? 
        'layouts/navigation/collapsible_elements/signed_in_links'
      else
        'layouts/navigation/collapsible_elements/non_signed_in_links'
      end
    end
    
  end

app/helpers/posts_feed_helper.rb
module PostsFeedHelper
end

app/helpers/posts_helper.rb
module PostsHelper
    #def post_likes_url(id:)
     #   polymorphic_url([:likes, id], only_path: true)
      #end
    #def post_likes_path(post)
     #   post_likes_url(id: post.id)
    #end
    
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/index.html.erb
<div class="container d-flex justify-content-center align-items-center vh-100">
  <div class="text-center">
    <h1 style="color: #3498db;">Welcome to 2P!</h1>
    <h3 style="color: #e74c3c;">2P stands for Portal Project..</h3>
    <br>
    <h4 style="color: #27ae60;">This is an application for connecting with people with the same interests!</h4>
    <h4 style="color: #f39c12;">Join the team by signing up to our platform, get access to all the fantastic features! :)</h4>
    <h3 style="color: #8e44ad;">Click on the service that you'd like to use!</h3>
    <h1 style="color: #e67e22;">See you on board!</h1>
    <%= link_to 'Go to Posts', posts_feed_index_path, class: 'btn btn-primary rounded-pill', id: 'posts-link', data: { signed_in: user_signed_in? } %>
    <%= link_to 'Go to Messenger', rooms_path, class: 'btn btn-primary rounded-pill', id: 'chats-link', data: { signed_in: user_signed_in? } %>
    <%= link_to "Contact List", contacts_path, class: 'btn btn-primary rounded-pill', id: 'contacts-link', data: { signed_in: user_signed_in? } %>
    <div class="flex justify-between">
  <% if user_signed_in? %>
    <!--<div>
      Signed in as <%= current_user.email %>. <%= button_to "Sign out", destroy_user_session_path, method: :delete, class: "text-blue-500" %>
      <%= link_to "All messages", rooms_path, class: "text-blue-500" %>
    </div> -->
    <br> <br>
    <div> <strong> Notifications: </strong></div>
    <%= turbo_frame_tag "notifications", src: notifications_path %> 
    <% if @notifications.present? %>
    <% @notifications.each do |notification| %>
      <%= render partial: 'notifications/notification', locals: { notification: notification } %>
    <% end %>
  <% else %>
    <p>No notifications</p>
  <% end %>
  <% else %>
    <%= link_to "Sign in", login_path , class: "text-blue-500" %>
  <% end %>
</div>
  </div>
</div>


<script>
const postsLink = document.getElementById('posts-link');
const chatsLink = document.getElementById('chats-link');
const contactsLink = document.getElementById('contacts-link');

const checkSignInAndRedirect = function(event, link) {
  const isUserSignedIn = link.dataset.signedIn === 'true';

  if (!isUserSignedIn) {
    alert('You need to sign up/in first!');
    event.preventDefault(); 
    window.location.href = '/login'; //  sign-in path.
  }
};

postsLink.addEventListener('click', function(event) {
  const isPostsLinkSignedIn = postsLink.dataset.signedIn === 'true';

  if (!isPostsLinkSignedIn) {
    alert('You need to sign up/in first to access Posts!'); 
    event.preventDefault();
    window.location.href = '/login';
  }
});

chatsLink.addEventListener('click', function(event) {
  const isChatsLinkSignedIn = chatsLink.dataset.signedIn === 'true';

  if (!isChatsLinkSignedIn) {
    alert('You need to sign up/in first to access Chats!'); 
    event.preventDefault();
    window.location.href = '/login';
  }
});

contactsLink.addEventListener('click', function(event) {
  const isContactsLinkSignedIn = contactsLink.dataset.signedIn === 'true';

  if (!isContactsLinkSignedIn) {
    alert('You need to sign up/in first to access Contacts!'); 
    event.preventDefault();
    window.location.href = '/login';
  }
});

</script>